import Footer from "@/components/Footer";
import Navbar from "../components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={...inter.className + " text-[#fff] flex flex-col min-h-screen"}>
      <div className="bg-[#000] h-[100vh] w-full absolute z-[-1]"></div>
        <div className="bg-[url('/images/background.png')] bg-contain bg-no-repeat bg-center h-[100vh] w-full absolute z-[-1]"></div>
        <Navbar/>
        <div className="flex-1 flex flex-col">
        {children}</div>    
        <Footer/>
      </body>
    </html>
  );
}
